apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ochacafe
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - kafka.shukawam.me
      secretName: shukawam-tls-secret-kafka
  rules:
    - host: kafka.shukawam.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ochacafe-bridge-service
                port:
                  number: 8080
